"""Catalogue-scale regression sweep.

The per-pair `/v1/scan` path answers "did this rendition introduce a flash?".
This module answers the question a distribution QC team actually has: across
every title and every rendition we are about to ship, which ones introduced a
photosensitivity violation their approved master never had?

That is a different computation, not a bigger loop. The published criteria are
evaluated inside ClickHouse over every transition measurement in the catalogue
in a single pass, and the parent/child isolation happens in the same query. The
SQL is held to the reference Python detector by `tests/test_sql_parity.py`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .clickhouse_mcp import ClickHouseMcp, timeline_sql


SQL_PATH = Path(__file__).resolve().parent.parent / "sql" / "006_catalogue_regression.sql"

_COMMENT = re.compile(r"/\*.*?\*/", re.S)


def catalogue_sql() -> str:
    """The exact SQL shipped in the repository, comments stripped for transport."""
    raw = SQL_PATH.read_text(encoding="utf-8")
    return _COMMENT.sub("", raw).strip().rstrip(";")


def scale_sql() -> str:
    """Corpus shape, so the product can state the size it actually searched."""
    return (
        "SELECT count() AS transitions, uniqExact(asset_id) AS assets, "
        "uniqExact(lineage_id) AS titles, uniqExact(transform) AS transforms "
        "FROM safe_frame.transitions"
    )


def _decode(result: dict[str, Any]) -> list[dict[str, Any]]:
    if result["is_error"]:
        raise RuntimeError(f"mcp-clickhouse returned an error: {result['content']}")
    text = "\n".join(str(item.get("text", "")) for item in result["content"])
    if not text.strip():
        return []
    decoded: Any = json.loads(text)
    if isinstance(decoded, str):
        decoded = json.loads(decoded)
    if isinstance(decoded, dict) and "columns" in decoded and "rows" in decoded:
        columns = list(decoded["columns"])
        return [dict(zip(columns, row)) for row in decoded["rows"]]
    if isinstance(decoded, list):
        return decoded
    if isinstance(decoded, dict):
        return [decoded]
    raise RuntimeError(f"unexpected mcp-clickhouse payload: {text[:400]}")


async def sweep() -> dict[str, Any]:
    """Run the catalogue sweep and the corpus-shape query through official MCP.

    Returns the isolated regressions plus the size of the corpus they were
    isolated from, so a reader can see the search was catalogue-wide rather
    than a lookup of a single prepared pair.
    """
    results, timing = await ClickHouseMcp().query_many([catalogue_sql(), scale_sql()])
    sweep_result, scale_result = results
    rows = _decode(sweep_result)
    scale = _decode(scale_result)
    shape = scale[0] if scale else {}

    by_transform: dict[str, int] = {}
    by_rule: dict[str, int] = {}
    for row in rows:
        transform = str(row.get("transform", "unknown"))
        by_transform[transform] = by_transform.get(transform, 0) + 1
        rule = str(row.get("rule", "unknown"))
        by_rule[rule] = by_rule.get(rule, 0) + 1

    return {
        "regressions": rows,
        "regression_count": len(rows),
        "affected_titles": len({row.get("lineage_id") for row in rows}),
        "by_rule": dict(sorted(by_rule.items(), key=lambda kv: -kv[1])),
        "by_transform": dict(sorted(by_transform.items(), key=lambda kv: -kv[1])),
        "rules_evaluated": ["general_flash", "red_flash"],
        "corpus": {
            "transitions": int(shape.get("transitions", 0) or 0),
            "assets": int(shape.get("assets", 0) or 0),
            "titles": int(shape.get("titles", 0) or 0),
            "transforms": int(shape.get("transforms", 0) or 0),
            "provenance": "self-authored synthetic catalogue, generated by sql/005_catalogue_generator.sql",
        },
        "timing": {
            # Split so neither number flatters the other: spawning the official
            # stdio MCP server costs seconds no matter how fast the SQL is.
            "mcp_setup_ms": timing.get("mcp_setup_ms"),
            "query_ms": timing.get("query_ms"),
            "note": "mcp_setup_ms is the official mcp-clickhouse subprocess handshake; query_ms covers both statements",
        },
        "decision_source": "clickhouse_sql_via_official_mcp",
        "criteria_source": "sql/006_catalogue_regression.sql",
        "parity": "tests/test_sql_parity.py holds this SQL to safe_frame.detector",
        "certified": False,
        "mcp": sweep_result,
    }


async def timeline(parent_asset: str, child_asset: str) -> dict[str, Any]:
    """Second-by-second qualifying-transition counts for one master/rendition pair.

    Returned as two aligned tracks over a shared scale so the comparison is
    honest: the same axis, the same units, the criterion drawn as one line
    across both. The criterion itself is returned rather than hard-coded in the
    page, so the chart cannot drift from the rule the database applied.
    """
    result = await ClickHouseMcp().query(timeline_sql(parent_asset, child_asset))
    rows = _decode(result)

    tracks: dict[str, dict[int, dict[str, int]]] = {parent_asset: {}, child_asset: {}}
    for row in rows:
        asset = str(row.get("asset_id", ""))
        if asset not in tracks:
            continue
        tracks[asset][int(row.get("second", 0) or 0)] = {
            "general_flash": int(row.get("general_flash", 0) or 0),
            "red_flash": int(row.get("red_flash", 0) or 0),
        }

    def series(asset: str) -> dict[str, Any]:
        seconds = tracks[asset]
        span = max(seconds) + 1 if seconds else 0
        return {
            "asset_id": asset,
            "seconds": span,
            "general_flash": [seconds.get(i, {}).get("general_flash", 0) for i in range(span)],
            "red_flash": [seconds.get(i, {}).get("red_flash", 0) for i in range(span)],
        }

    return {
        "parent": series(parent_asset),
        "child": series(child_asset),
        # Drawn as the threshold line on the chart. More than this many
        # qualifying transitions inside one second is a violation.
        "criterion_transitions_per_second": 6,
        "decision_source": "clickhouse_sql_via_official_mcp",
        "note": "counts are qualifying transitions per second, per rule, as the criteria define them",
    }
