"""Immutable evidence records. Generated prose is only a view over these records."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from hashlib import sha256
from typing import Literal
from urllib.parse import urlparse

Stance = Literal["supports", "contradicts", "neutral"]


def utc_now() -> datetime:
    return datetime.now(UTC)


def stable_claim_id(subject: str, predicate: str, object_: str) -> str:
    canonical = "\x1f".join(part.strip() for part in (subject, predicate, object_))
    return "clm_" + sha256(canonical.encode("utf-8")).hexdigest()[:24]


@dataclass(frozen=True, slots=True)
class Source:
    url: str
    domain: str
    excerpt: str
    retrieved_at: datetime = field(default_factory=utc_now)
    verified: bool = False

    def __post_init__(self) -> None:
        parsed = urlparse(self.url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            raise ValueError("source url must be an absolute http(s) URL")
        normalized_domain = parsed.hostname.lower() if parsed.hostname else ""
        if self.domain.lower().removeprefix("www.") != normalized_domain.removeprefix("www."):
            raise ValueError("source domain must match the URL hostname")
        if not self.excerpt.strip():
            raise ValueError("source excerpt is required")


@dataclass(frozen=True, slots=True)
class Claim:
    claim_id: str
    claim_text: str
    subject: str
    agent_id: str
    stance: Stance
    sources: tuple[Source, ...] = ()
    retrieved_at: datetime = field(default_factory=utc_now)
    confidence_basis: str = ""

    def __post_init__(self) -> None:
        if not self.claim_id.startswith("clm_"):
            raise ValueError("claim_id must be generated by stable_claim_id")
        if not self.claim_text.strip() or not self.subject.strip() or not self.agent_id.strip():
            raise ValueError("claim text, subject, and agent id are required")
        if not self.confidence_basis.strip():
            raise ValueError("confidence_basis must explain why the claim is believed")

    @property
    def is_decisive_eligible(self) -> bool:
        return any(source.verified for source in self.sources)

    @property
    def independent_domains(self) -> frozenset[str]:
        return frozenset(
            source.domain.lower().removeprefix("www.")
            for source in self.sources
            if source.verified
        )

